### ISSUE TITLE
Config file option to provide settings for element properties

### ISSUE THREAD

**Issue by shortcipher3** [nnstreamer/nnstreamer#3904]
**Is your feature request related to a problem? Please describe.**

Some of the filters such as `tensor_decoder` have a lot of properties.  It would be nice to have a config file to specify these, this way when specifying lots of config settings it doesn't clutter the code or command line, which would make the pipeline easier to read for new users.

For example, [this single element from the object detection example](https://github.com/nnstreamer/nnstreamer-example/blob/4efa166d2062d7f620202bb2c3ed663e11fa2683/bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh#L7) is 166 columns:

```bash
tensor_decoder mode=bounding_boxes option1=mobilenet-ssd option2=tflite_model/coco_labels_list.txt option3=tflite_model/box_priors.txt option4=640:480 option5=300:300
```

Where best practice for bash scripts is to keep the line under 80 columns.

**Describe the solution you'd like**

These options could easily be specified in a config file, so the element reads:

```bash
tensor_decoder config-file=object_detection.config
```

And the contents of the config file are as follows:

```yaml
mode: bounding_boxes
option1: mobilenet-ssd
option2: tflite_model/coco_labels_list.txt
option3: tflite_model/box_priors.txt
option4: 640:480
option5: 300:300
```

This would make the configuration more readable and less error prone as well.
